name 'etcd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures etcd'
long_description 'Installs/Configures etcd'
version '0.1.0'
depends 'coreip-common'
