name 'bind'
maintainer 'Jonathan Turner'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bind for Core IP Vagrant setup'
long_description 'Installs/Configures bind for Core IP Vagrant setup'
version '0.1.0'
depends 'coreip-common'
